apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 8
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: santanarael/minha-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: PG_HOST
          value: postgres-service
        - name: PG_PORT
          value: "5432"
        - name: PG_USER
          value: SantanaRael
        - name: PG_PASSWORD
          value: "1234"
        - name: PG_DB
          value: meu-banco

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 30303
      targetPort: 3000
  type: LoadBalancer 
  