apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="style.css">
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet">
        <title>CRUD - Gerenciamento de Pessoas</title>
    </head>
    <body>
        <div class="container">
            <header class="nav">
                <h1>CRUD - Gerenciamento de Pessoas</h1>
                <nav class="botoes-dep">
                    <div class="btn consultar" onclick="mostrarDiv('tabela')">
                        <i class='bx bx-show'></i>Consultar
                    </div>
                    <div class="btn incluir" onclick="mostrarDiv('Cadastrar')">
                        <i class='bx bx-add-to-queue'></i>Incluir
                    </div>
                    <div class="btn alterar" onclick="mostrarDiv('AtualizaCadastro')">
                        <i class='bx bx-edit'></i>Alterar
                    </div>
                    <div class="btn excluir" onclick="mostrarDiv('deletaCadastro')">
                        <i class='bx bx-trash'></i>Excluir
                    </div>
                </nav>
            </header>

            <div class="table">
                <table class="content" id="tabela">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>CPF</th>
                        </tr>
                    </thead>
                    <tbody id="tabela-dados"></tbody>
                </table>
            </div>

            <div class="content" id="Cadastrar">
                <h2>Cadastro de Usuário</h2>
                <form>
                    <div class="form-group">
                        <label for="nome">Nome:</label>
                        <input type="text" id="nome" name="nome" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" id="email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="cpf">CPF:</label>
                        <input type="text" id="cpf" name="cpf" required>
                    </div>
                    <div class="form-group">
                        <input id="submit" type="submit" value="Cadastrar">
                    </div>
                </form>
            </div>

            <div class="content" id="AtualizaCadastro">
                <h2>Alterar Usuário</h2>
                <div class="form-group">
                    <label for="userId">ID do Usuário:</label>
                    <input type="text" id="userId" placeholder="Digite o ID do usuário">
                    <button id="buscarPeloId">Buscar</button>
                </div>
                <div class="form-group">
                    <label for="userName">Nome:</label>
                    <input type="text" id="userName" placeholder="Nome do usuário">
                </div>
                <div class="form-group">
                    <label for="userEmail">Email:</label>
                    <input type="text" id="userEmail" placeholder="Email do usuário">
                </div>
                <div class="form-group">
                    <label for="userCpf">CPF:</label>
                    <input type="text" id="userCpf" placeholder="CPF do usuário">
                </div>
                <button id="alterar">Alterar</button>
            </div>

            <div class="content" id="deletaCadastro">
                <h2>Apagar Usuário</h2>
                <div class="form-group">
                    <label for="userId">ID do Usuário:</label>
                    <input type="text" id="userIdDel" placeholder="Digite o ID do usuário">
                    <button id="apagarUser">Apagar</button>
                </div>
            </div>
        </div>

        <script src="script.js"></script>
    </body>
    </html>


  style.css: |
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-color: #f4f4f4;
    }

    .container {
      max-width: 1200px;
      margin: 0 auto;
      padding: 20px;
    }

    .nav {
      background-color: #333;
      color: #fff;
      text-align: center;
      padding: 10px 0;
    }
    .nav h1 {
      margin: 0;
    }

    .botoes-dep {
      display: flex;
      justify-content: center;
    }

    .btn {
      margin: 0 10px;
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 10px 20px;
      cursor: pointer;
      border-radius: 5px;
      font-size: 16px;
    }

    .table {
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 5px rgba(0, 0, 0, 0.2);
      margin-top: 20px;
      overflow-x: auto;
    }

    .content {
      padding: 20px;
      display: none;
    }

    table {
      width: 100%;
      border-collapse: collapse;
    }

    th {
      padding: 8px 12px;
      border: 1px solid #ccc;
      text-align: left;
      width: 50%;
    }

    td {
      padding: 8px 12px;
      border: 1px solid #ccc;
      text-align: left;
      width: 50%;
    }

    #tabela td:nth-child(1) {
      width: 100px;
    }
    #tabela th:nth-child(1) {
      width: 100px;
    }

    #tabela td:nth-child(4) {
      min-width: 150px;
    }
    #tabela th:nth-child(4) {
      min-width: 150px;
    }

    thead {
      background-color: #333;
      color: #fff;
    }

    tr:nth-child(even) {
      background-color: #f2f2f2;
    }

    .form-group {
      margin: 10px 0;
    }

    form label {
      font-weight: bold;
      color: #333;
      display: block;
    }
    form input[type=text] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      margin-top: 5px;
    }
    form input[type=text]:focus {
      outline: none;
      border-color: #4CAF50;
    }
    form input[type=email] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      margin-top: 5px;
    }
    form input[type=email]:focus {
      outline: none;
      border-color: #4CAF50;
    }

    input[type=text i] {
      width: 100%;
      padding: 10px;
      border: 1px solid #ccc;
      border-radius: 5px;
      margin-top: 5px;
    }

    #submit {
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      width: 100%;
      margin-top: 10px;
    }
    #submit:hover {
      background-color: #45a049;
    }

    #buscarPeloId {
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      width: 100%;
      margin-top: 10px;
    }
    #buscarPeloId:hover {
      background-color: #45a049;
    }

    #alterar {
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      width: 100%;
      margin-top: 10px;
    }
    #alterar:hover {
      background-color: #45a049;
    }

    #apagarUser {
      background-color: #4CAF50;
      color: #fff;
      border: none;
      padding: 10px 20px;
      border-radius: 5px;
      cursor: pointer;
      width: 100%;
      margin-top: 10px;
    }
    #apagarUser:hover {
      background-color: #45a049;
    }

    @media (max-width: 768px) {
      .btn {
        font-size: 14px;
      }
      .form-group {
        margin: 5px 0;
      }
      form input[type=text] {
        padding: 8px;
      }
      form input[type=email] {
        padding: 8px;
      }
      th {
        padding: 6px 10px;
        width: 100px;
      }
      td {
        padding: 6px 10px;
        width: 100px;
      }
    }


    @media (max-width: 468px) {
      .container {
        padding: 0;
      }

      .botoes-dep {
        display: grid;
        grid-template-columns: repeat(2, 1fr);
        grid-template-rows: repeat(2, 1fr);
        grid-column-gap: 0px;
        grid-row-gap: 0px;
        
      }

      .btn {
        margin: 10px;
      }
    }

  script.js: |
    let consultar = document.querySelector(".botoes-dep").children[0];
    let incluir = document.querySelector(".botoes-dep").children[1];

    let containerCadastrar = document.querySelector("#Cadastrar");


    let cadastrar = document.querySelector("#submit")

    const url = "http://192.168.49.2:30303/clientes/";


    //essa função faz um get na API e recebe o resultado na variavel response.data
    function consultarTodos(){
        axios.get(url)
        .then(response => {
            const dados = response.data;
            criarTabela(dados)
        })
        .catch( error => console.log(error))
    }


    //Essa função transforma o Array em tabela
    function criarTabela(dados) {
        
      var tabela = document.querySelector("table");
      var tbody = tabela.querySelector("tbody");

        if(tbody.innerHTML != ""){
            tbody.innerHTML = "";
            criarTabela(dados)
        }else{
            for (var i = 0; i < dados.length; i++) {
                var row = tbody.insertRow();
                var cell1 = row.insertCell(0);
                var cell2 = row.insertCell(1);
                var cell3 = row.insertCell(2);
                var cell4 = row.insertCell(3);
        
                cell1.innerHTML = dados[i].id;
                cell2.innerHTML = dados[i].nome;
                cell3.innerHTML = dados[i].email;
                cell4.innerHTML = dados[i].cpf;
            }
        }


    }


    //aqui fazemos a função constultar todos ser executada sempre que for clicado no botão consultar
    consultar.addEventListener("click", function(){

        consultarTodos()
    });

    //aqui temos uma função que usa o metodo post na API que envia  um json com as informações dos inputs
    function cadastraCliente(){

        //esse array pega os valores dos inputs pelo id
        const dadosDosInputs = {
        nome: nome.value,
        email: email.value,
        cpf: cpf.value
        }

        axios.post(url, dadosDosInputs)
        .then(response => {
            console.log(response.data)
        })
        .catch(error => console.log(error))
    }

    cadastrar.addEventListener("click", function(){
        cadastraCliente()
        alert("Usuario adicionado com sucesso!")

    });


    function consultarPeloId(){
        
        
        axios.get(`${url}${userId.value}` )
        .then(response => {
            const dados = response.data;
            userName.value = dados[0].nome;
            userEmail.value = dados[0].email;
            userCpf.value  = dados[0].cpf;
        })
        .catch( error => console.log(error))
    }

    buscarPeloId.addEventListener("click", function(){
        consultarPeloId()
    });

    function alterarCliente(){
        const dadosDosInputs = {
            nome: userName.value,
            email: userEmail.value,
            cpf: userCpf.value
            }
            console.log(dadosDosInputs)
        axios.patch(`${url}${userId.value}`, dadosDosInputs)
        .then(response => {
            alert("Usuario alterado com sucesso")
        })
        .catch(error => console.log(error))
        
    }

    alterar.addEventListener("click", function(){
        alterarCliente()
    });

    function deletarCliente(){
        axios.delete(`${url}${userIdDel.value}`)
        .then(response => {
            alert("Usuario apagado com sucesso!")
        })
        .catch(error => console.log(error))
    }


    apagarUser.addEventListener("click", function(){
        deletarCliente()
    });


    function mostrarDiv(id) {
        // Oculta todas as divs de conteúdo
        var divs = document.getElementsByClassName('content');
        for (var i = 0; i < divs.length; i++) {
            divs[i].style.display = 'none';
        }

        // Mostra a div correspondente ao item clicado
        var div = document.getElementById(id);
        div.style.display = 'block';
    }




